language: python
sudo: false
branches:
only:
  - master
python:
  - 3.6

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes scipy numpy scikit-learn pip
  - pip install pysal

script:
  - python setup.py install
  - nosetests --verbose test_skater.py

notifications:
    email: 
        recipients:
            - levi.john.wolf+travis@gmail.com
        on_change: always
        on_failure: always
